### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-js-booleans-and-comparators#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://elite-purpose.surge.sh/).

I didn't know what confirm was, and when I learned, I wasn't sure how to work it in. Maybe take it out of this project altogether. It was also tempting to get carried away with loops and innerHTML, but I didn't.

**Comment by chrisvfritz** [comment]
Magnifique! :shipit: I survived!!! :tada:
